name: Revisar boletos de Leiva

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  revisar:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.TOKEN }}
      CHATID: ${{ secrets.CHATID }}

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar script
        run: node index.js
